### ISSUE TITLE
Layout de la boite de dialogue

### ISSUE THREAD

**Issue by julienfastre** [Champs-Libres/QgisGeoJSONExportPlugin#2]
![export-plugin](https://cloud.githubusercontent.com/assets/345600/6145681/acf62740-b1e4-11e4-85b0-4112d0544a0e.png)

Est-ce qu'il serait possible de  
- mieux aligner "Protocole"
- traduire les champs 

(bug mineur)

**Comment by marcu** [comment]
Une nouvelle fenêtre a été créée. Est-ce mieux ?

**Comment by marcu** [comment]
Normalement c'est réglé.
