### ISSUE TITLE
Window layout to be redesigned

### ISSUE THREAD

**Issue by pcav** [Champs-Libres/QgisGeoJSONExportPlugin#5]
Resizing does not work well, one field is hidden behind others, etc.
See attached image.
![json](https://cloud.githubusercontent.com/assets/691842/6185581/feac766e-b367-11e4-9e57-3702dc6dd84b.png)

**Comment by marcu** [comment]
I extend the parameters block. I hope this will fix this bug. I use Qt designor on macos.

**Comment by marcu** [comment]
Fixed !
